name: app_fit
description: Local-first App Fit with a native Health Connect bridge.
publish_to: none
version: 0.1.0+1
environment:
  sdk: ^3.13.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  image_picker: ^1.2.4
  share_plus: ^13.3.1
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  path: ^1.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.0
flutter:
  uses-material-design: true
